class MidiPico
  module Keycodes
    # HID Usage ID (USB HID Keyboard/Keypad Page 0x07)
    KC_A     = Action::Keycode.new(0x04)
    KC_B     = Action::Keycode.new(0x05)
    KC_C     = Action::Keycode.new(0x06)
    KC_D     = Action::Keycode.new(0x07)
    KC_E     = Action::Keycode.new(0x08)
    KC_F     = Action::Keycode.new(0x09)
    KC_G     = Action::Keycode.new(0x0A)
    KC_H     = Action::Keycode.new(0x0B)
    KC_I     = Action::Keycode.new(0x0C)
    KC_J     = Action::Keycode.new(0x0D)
    KC_K     = Action::Keycode.new(0x0E)
    KC_L     = Action::Keycode.new(0x0F)
    KC_M     = Action::Keycode.new(0x10)
    KC_N     = Action::Keycode.new(0x11)
    KC_O     = Action::Keycode.new(0x12)
    KC_P     = Action::Keycode.new(0x13)
    KC_Q     = Action::Keycode.new(0x14)
    KC_R     = Action::Keycode.new(0x15)
    KC_S     = Action::Keycode.new(0x16)
    KC_T     = Action::Keycode.new(0x17)
    KC_U     = Action::Keycode.new(0x18)
    KC_V     = Action::Keycode.new(0x19)
    KC_W     = Action::Keycode.new(0x1A)
    KC_X     = Action::Keycode.new(0x1B)
    KC_Y     = Action::Keycode.new(0x1C)
    KC_Z     = Action::Keycode.new(0x1D)

    KC_1     = Action::Keycode.new(0x1E)
    KC_2     = Action::Keycode.new(0x1F)
    KC_3     = Action::Keycode.new(0x20)
    KC_4     = Action::Keycode.new(0x21)
    KC_5     = Action::Keycode.new(0x22)
    KC_6     = Action::Keycode.new(0x23)
    KC_7     = Action::Keycode.new(0x24)
    KC_8     = Action::Keycode.new(0x25)
    KC_9     = Action::Keycode.new(0x26)
    KC_0     = Action::Keycode.new(0x27)

    KC_ENTER = Action::Keycode.new(0x28)
    KC_ESC   = Action::Keycode.new(0x29)
    KC_BSPC  = Action::Keycode.new(0x2A)
    KC_TAB   = Action::Keycode.new(0x2B)
    KC_SPC   = Action::Keycode.new(0x2C)
    KC_MINUS = Action::Keycode.new(0x2D)
    KC_EQUAL = Action::Keycode.new(0x2E)
    KC_LBRC  = Action::Keycode.new(0x2F)
    KC_RBRC  = Action::Keycode.new(0x30)
    KC_BSLS  = Action::Keycode.new(0x31)
    KC_SCLN  = Action::Keycode.new(0x33)
    KC_QUOT  = Action::Keycode.new(0x34)
    KC_GRV   = Action::Keycode.new(0x35)
    KC_COMM  = Action::Keycode.new(0x36)
    KC_DOT   = Action::Keycode.new(0x37)
    KC_SLSH  = Action::Keycode.new(0x38)

    KC_F1    = Action::Keycode.new(0x3A)
    KC_F2    = Action::Keycode.new(0x3B)
    KC_F3    = Action::Keycode.new(0x3C)
    KC_F4    = Action::Keycode.new(0x3D)
    KC_F5    = Action::Keycode.new(0x3E)
    KC_F6    = Action::Keycode.new(0x3F)
    KC_F7    = Action::Keycode.new(0x40)
    KC_F8    = Action::Keycode.new(0x41)
    KC_F9    = Action::Keycode.new(0x42)
    KC_F10   = Action::Keycode.new(0x43)
    KC_F11   = Action::Keycode.new(0x44)
    KC_F12   = Action::Keycode.new(0x45)

    KC_RIGHT = Action::Keycode.new(0x4F)
    KC_LEFT  = Action::Keycode.new(0x50)
    KC_DOWN  = Action::Keycode.new(0x51)
    KC_UP    = Action::Keycode.new(0x52)
    KC_DEL   = Action::Keycode.new(0x4C)
    KC_HOME  = Action::Keycode.new(0x4A)
    KC_END   = Action::Keycode.new(0x4D)
    KC_PGUP  = Action::Keycode.new(0x4B)
    KC_PGDN  = Action::Keycode.new(0x4E)
  end
end
